### ISSUE TITLE
read error on Windows 10

### ISSUE THREAD

**Issue by vashe-blagorodie** [redphx/joydance#56]
Get an error on windows10,  if try to Connect, defender is off

Error handling request
Traceback (most recent call last):
  File "aiohttp\web_protocol.py", line 435, in _handle_request
  File "aiohttp\web_app.py", line 504, in _handle
  File "dance.py", line 313, in websocket_handler
    joycon_list = await get_joycon_list(request.app)
  File "dance.py", line 76, in get_joycon_list
    joycon = JoyCon(dev['vendor_id'], dev['product_id'], dev['serial'])
  File "pycon\joycon.py", line 46, in __init__
    self._read_joycon_data()
  File "pycon\joycon.py", line 137, in _read_joycon_data
    color_data = self._spi_flash_read(0x6050, 6)
  File "pycon\joycon.py", line 106, in _spi_flash_read
    ack, report = self._send_subcmd_get_response(b'\x10', argument)
  File "pycon\joycon.py", line 94, in _send_subcmd_get_response
    report = self._read_input_report()
  File "pycon\joycon.py", line 72, in _read_input_report
    return bytes(self._joycon_device.read(self._INPUT_REPORT_SIZE))
  File "hid.pyx", line 219, in hid.device.read
OSError: read error

**Comment by vashe-blagorodie** [comment]
find out, that if joycon is just added as new bluetuth device, so the all work properly. But if device already added and then activated, so the error occur

**Comment by BroJac5246** [comment]
> find out, that if joycon is just added as new bluetuth device, so the all work properly. But if device already added and then activated, so the error occur

Huh... I'd been having issues like that but for me I think it was Windows not pairing. Either way, glad to see you figured it out!

**Comment by vashe-blagorodie** [comment]
> > find out, that if joycon is just added as new bluetuth device, so the all work properly. But if device already added and then activated, so the error occur
> 
> Huh... I'd been having issues like that but for me I think it was Windows not pairing. Either way, glad to see you figured it out!

I think that pairing in this cases is different, but I have no idea how pairing bluetuth wokrs, and so the way look futher.
