### ISSUE TITLE
ModuleNotFound Error: No module named ´_ctypes

### ISSUE THREAD

**Issue by Zthrowaway** [redphx/joydance#59]
OS: VanillaOS Orchid, x64 - Branched off Ubuntu 22.04

Output:
```
Defaulting to user installation because normal site-packages is not writeable
  Collecting websockets==10.2 (from -r requirements.txt (line 1))
  Using cached websockets-10.2.tar.gz (83 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-w9i2f22g/websockets.egg-info
      writing /tmp/pip-modern-metadata-w9i2f22g/websockets.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-w9i2f22g/websockets.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-modern-metadata-w9i2f22g/websockets.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-w9i2f22g/websockets.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-w9i2f22g/websockets.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-w9i2f22g/websockets.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-w9i2f22g/websockets-10.2.dist-info'
      Traceback (most recent call last):
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 33, in <module>
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/command/dist_info.py", line 97, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 302, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 861, in get_command_obj
          klass = self.get_command_class(command)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mxpxqo43/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 715, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
                                              ^^^^^^^^^
        File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
          module = import_module(match.group('module'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-mxpxqo43/normal/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 27, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/tmp/pip-build-env-mxpxqo43/normal/lib/python3.12/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/usr/local/lib/python3.12/ctypes/__init__.py", line 8, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

This does _not_ seem to be an issue with Python, as I have 3.12.3 (latest) installed.

**Comment by BroJac5246** [comment]
Ugh I hated when I installed JoyDance on Ubuntu; I still have no idea how I managed to do it...

> This does not seem to be an issue with Python, as I have 3.12.3 (latest) installed.

JoyDance doesn't play well with newer Python versions. I think you can make it work on 3.11 (I know it works on Windows), but 3.12 doesn't typically work. If you want, you could try creating a venv running an earlier version.

It sometimes helps to try to manually install a module using pip, but I don't remember if that worked on Ubuntu (I think I did that like a year ago so I don't remember all the steps, sorry).

**Comment by Zthrowaway** [comment]
@BroJac5246 Just a notif that I saw this - accidentally deleted my linux partition (whoops, good thing I back up files) so it may be a sec before I can say how that plays out. I will try it though, and thanks for the advice!
