### ISSUE TITLE
JoyDance crashing after attempt

### ISSUE THREAD

**Issue by TheWooomy** [redphx/joydance#62]
So after like two tries on connecting the joycon to the game (jd 2017 pc), the cmd prompt just crashes

`{'pairing_method': 'old', 'host_ip_addr': '192.168.1.84', 'console_ip_addr': '192.168.1.84', 'pairing_code': '', 'joycon_serial': '64b5c6d8616d'}
64b5c6d8616d PairingState.CONNECTING
Traceback (most recent call last):
  File "C:\Users\cerda\Downloads\joydance-0.5.2\joydance-0.5.2\joydance\__init__.py", line 416, in connect_ws
    async with websockets.connect(
  File "C:\Users\cerda\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\client.py", line 517, in __aenter__
    return await self
           ^^^^^^^^^^
  File "C:\Users\cerda\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cerda\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1098, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cerda\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1118, in _create_connection_transport
    protocol = protocol_factory()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\cerda\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\client.py", line 69, in __init__
    super().__init__(**kwargs)
  File "C:\Users\cerda\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\protocol.py", line 235, in __init__
    self._drain_lock = asyncio.Lock(
                       ^^^^^^^^^^^^^
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'
64b5c6d8616d PairingState.ERROR_CONSOLE_CONNECTION
disconnected
Exception in thread Thread-107 (_update_input_report):
Traceback (most recent call last):
  File "C:\Users\cerda\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\cerda\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\cerda\Downloads\joydance-0.5.2\joydance-0.5.2\pycon\joycon.py", line 121, in _update_input_report
    while report[0] != 0x30:
          ~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
{'pairing_method': 'old', 'host_ip_addr': '192.168.1.84', 'console_ip_addr': '192.168.1.84', 'pairing_code': '', 'joycon_serial': '64b5c6d8616d'}` 

Thanks to this i can't get to connect the controller help pls

**Comment by BroJac5246** [comment]
Have you tried connecting to a game that isn't 2017 PC edition?

**Comment by TheWooomy** [comment]
> Have you tried connecting to a game that isn't 2017 PC edition?

yes, i just tried it on just dance 2020 edition on nintendo switch and when i press connect it says invalid pairing code even though it is correct

**Comment by BroJac5246** [comment]
> > Have you tried connecting to a game that isn't 2017 PC edition?
> 
> yes, i just tried it on just dance 2020 edition on nintendo switch and when i press connect it says invalid pairing code even though it is correct

Huh. I really don't know what would be causing this. 

You might have luck if you try on a different device, but otherwise I don't know how to fix this (though a solution probably exists that I don't know about, if you keep searching).
