### ISSUE TITLE
Off Brand Joycons

### ISSUE THREAD

**Issue by chiefscott** [redphx/joydance#67]
Has anyone gotten non-official joycons to work?

I bought some off ebay and can't get them to show up on the app.

Any insights?

I get an error when connecting them to my PC's bluetooth and before I return them wanted to see if anyone had any insight.

Here's the error I get:

Error handling request
Traceback (most recent call last):
  File "C:\Users\Scott\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\web_protocol.py", line 435, in handlerequest
    resp = await request_handler(request)
  File "C:\Users\Scott\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "dance.py", line 313, in websocket_handler
    joycon_list = await get_joycon_list(request.app)
  File "dance.py", line 76, in get_joycon_list
    joycon = JoyCon(dev['vendor_id'], dev['product_id'], dev['serial'])
  File "C:\Users\Scott\Downloads\joydance-0.5.2\pycon\joycon.py", line 46, in init
    self._read_joycon_data()
  File "C:\Users\Scott\Downloads\joydance-0.5.2\pycon\joycon.py", line 141, in readjoycon_data
    self._read_stick_calibration_data()
  File "C:\Users\Scott\Downloads\joydance-0.5.2\pycon\joycon.py", line 168, in readstick_calibration_data
    buf = self._spi_flash_read(user_stick_cal_addr, 9)
  File "C:\Users\Scott\Downloads\joydance-0.5.2\pycon\joycon.py", line 111, in spiflash_read
    raise IOError("Something else than the expected ACK was recieved!")
OSError: Something else than the expected ACK was recieved!

**Comment by BroJac5246** [comment]
Have you been able to try with real Joy-Cons?

**Comment by chiefscott** [comment]
I haven't yet. They're very expensive which is why I went with a cheaper brand hoping it'd work.

I'm afraid to buy a "Used" one because it just might be a priced up after market one.

**Comment by BroJac5246** [comment]
> I haven't yet. They're very expensive which is why I went with a cheaper brand hoping it'd work.
> 
> I'm afraid to buy a "Used" one because it just might be a priced up after market one.

Afaik off-brand Joy-Cons should work, but JoyDance is notoriously hard to set up correctly. My guess would be that it's a problem with your installation, but I can't really confirm that. If you want to mess with tweaking installed dependencies, looking up errors, etc. then you might be able to fix it but I can't help you with that and no one else is likely to respond to your issue. There are some websites that will let you connect your Joy-Con, which could help you confirm everything is working correctly for the Joy-Con. You could also try setting up JoyDance on a different device, which might help. Sorry I can't do more, but best of luck!

**Comment by chiefscott** [comment]
Could you recommend any of the websites that let you connect the joy cons?

My computer see's the JoyCons and I can connect them through my BT Adapter it's just JoyDance doesn't see them.

Any suggestions on tweaking the dependencies? I've looked up the errors through LLMs but it just gives me kind of generic advice.

**Comment by BroJac5246** [comment]
Sorry about the delay, you can try this website: https://tomayac.github.io/joy-con-webhid/demo/

I don't have any idea how to solve your specific errors. If you have Python experience then you could try debugging it yourself, but that's a pain. My only other suggestion would be to try installing JoyDance on a different device.

**Comment by chiefscott** [comment]
No worries. gonna just return them but ty for trying

**Comment by kzvdar42** [comment]
If someone stumbles on this issue in future, this error is fixed in my fork: https://github.com/kzvdar42/joydance
